INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Classic Milk Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Classic Milk Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Classic Milk Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Classic Milk Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Honeydew Milk Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Honeydew Milk Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Honeydew Milk Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Honeydew Milk Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Jasmine Milk Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Jasmine Milk Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Jasmine Milk Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Jasmine Milk Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Matcha Milk Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Matcha Milk Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Matcha Milk Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Matcha Milk Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Oolong Milk Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Oolong Milk Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Oolong Milk Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Oolong Milk Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Thai Milk Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Thai Milk Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Thai Milk Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Milk Tea', 'Thai Milk Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Green Apple Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Green Apple Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Green Apple Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Green Apple Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Lychee Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Lychee Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Lychee Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Lychee Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Mango Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Mango Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Mango Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Mango Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Peach Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Peach Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Peach Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Peach Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Pineapple Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Pineapple Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Pineapple Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Pineapple Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Strawberry Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Strawberry Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Strawberry Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Strawberry Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Watermelon Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Watermelon Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Watermelon Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Watermelon Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Wintermelon Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Wintermelon Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Wintermelon Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Wintermelon Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Passionfruit Tea', 0);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Passionfruit Tea', 1);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Passionfruit Tea', 2);
INSERT INTO items (category, name, item_size) VALUES ('Fruit Tea', 'Passionfruit Tea', 3);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Mango Smoothie', 0);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Mango Smoothie', 1);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Mango Smoothie', 2);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Mango Smoothie', 3);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Strawberry Smoothie', 0);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Strawberry Smoothie', 1);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Strawberry Smoothie', 2);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Strawberry Smoothie', 3);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Pineapple Smoothie', 0);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Pineapple Smoothie', 1);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Pineapple Smoothie', 2);
INSERT INTO items (category, name, item_size) VALUES ('Smoothies', 'Pineapple Smoothie', 3);
INSERT INTO items (category, name, item_size) VALUES ('Frappe', 'Mocha Frappe', 0);
INSERT INTO items (category, name, item_size) VALUES ('Frappe', 'Mocha Frappe', 1);
INSERT INTO items (category, name, item_size) VALUES ('Frappe', 'Mocha Frappe', 2);
INSERT INTO items (category, name, item_size) VALUES ('Frappe', 'Mocha Frappe', 3);
INSERT INTO items (category, name, item_size) VALUES ('Frappe', 'Caramel Frappe', 0);
INSERT INTO items (category, name, item_size) VALUES ('Frappe', 'Caramel Frappe', 1);
INSERT INTO items (category, name, item_size) VALUES ('Frappe', 'Caramel Frappe', 2);
INSERT INTO items (category, name, item_size) VALUES ('Frappe', 'Caramel Frappe', 3);
INSERT INTO items (category, name, item_size) VALUES ('Slush', 'Blueberry Slush', 0);
INSERT INTO items (category, name, item_size) VALUES ('Slush', 'Blueberry Slush', 1);
INSERT INTO items (category, name, item_size) VALUES ('Slush', 'Blueberry Slush', 2);
INSERT INTO items (category, name, item_size) VALUES ('Slush', 'Blueberry Slush', 3);
INSERT INTO items (category, name, item_size) VALUES ('Slush', 'Watermelon Slush', 0);
INSERT INTO items (category, name, item_size) VALUES ('Slush', 'Watermelon Slush', 1);
INSERT INTO items (category, name, item_size) VALUES ('Slush', 'Watermelon Slush', 2);
INSERT INTO items (category, name, item_size) VALUES ('Slush', 'Watermelon Slush', 3);
INSERT INTO items (category, name, item_size) VALUES ('Yakult', 'Strawberry Yakult', 0);
INSERT INTO items (category, name, item_size) VALUES ('Yakult', 'Strawberry Yakult', 1);
INSERT INTO items (category, name, item_size) VALUES ('Yakult', 'Strawberry Yakult', 2);
INSERT INTO items (category, name, item_size) VALUES ('Yakult', 'Strawberry Yakult', 3);
INSERT INTO items (category, name, item_size) VALUES ('Yakult', 'Mango Yakult', 0);
INSERT INTO items (category, name, item_size) VALUES ('Yakult', 'Mango Yakult', 1);
INSERT INTO items (category, name, item_size) VALUES ('Yakult', 'Mango Yakult', 2);
INSERT INTO items (category, name, item_size) VALUES ('Yakult', 'Mango Yakult', 3);
INSERT INTO items (category, name, item_size) VALUES ('Ice Cream', 'Chocolate Ice Cream', 0);
INSERT INTO items (category, name, item_size) VALUES ('Ice Cream', 'Chocolate Ice Cream', 1);
INSERT INTO items (category, name, item_size) VALUES ('Ice Cream', 'Chocolate Ice Cream', 2);
INSERT INTO items (category, name, item_size) VALUES ('Ice Cream', 'Chocolate Ice Cream', 3);
INSERT INTO items (category, name, item_size) VALUES ('Ice Cream', 'Vanilla Ice Cream', 0);
INSERT INTO items (category, name, item_size) VALUES ('Ice Cream', 'Vanilla Ice Cream', 1);
INSERT INTO items (category, name, item_size) VALUES ('Ice Cream', 'Vanilla Ice Cream', 2);
INSERT INTO items (category, name, item_size) VALUES ('Ice Cream', 'Vanilla Ice Cream', 3);

--ALTER SEQUENCE items_item_id_seq RESTART WITH 1;
----
--truncate table items cascade;